// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBisnvOFmDLFX4qkRCsgyxFB6I6rqVEP3o',
    appId: '1:404183473726:web:0d2ac298a2ed811f21bb6f',
    messagingSenderId: '404183473726',
    projectId: 'cw8-v2',
    authDomain: 'cw8-v2.firebaseapp.com',
    storageBucket: 'cw8-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiOJ72dviLmR4HPmGdCRQm027CygDZ0wI',
    appId: '1:404183473726:android:649fc37a2455f99e21bb6f',
    messagingSenderId: '404183473726',
    projectId: 'cw8-v2',
    storageBucket: 'cw8-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBpg_DEJEabygVQ5uL1HSuErnVYr0xAyE',
    appId: '1:404183473726:ios:9458789cbbb16e6621bb6f',
    messagingSenderId: '404183473726',
    projectId: 'cw8-v2',
    storageBucket: 'cw8-v2.firebasestorage.app',
    iosBundleId: 'com.example.cw8V2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBpg_DEJEabygVQ5uL1HSuErnVYr0xAyE',
    appId: '1:404183473726:ios:9458789cbbb16e6621bb6f',
    messagingSenderId: '404183473726',
    projectId: 'cw8-v2',
    storageBucket: 'cw8-v2.firebasestorage.app',
    iosBundleId: 'com.example.cw8V2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBisnvOFmDLFX4qkRCsgyxFB6I6rqVEP3o',
    appId: '1:404183473726:web:c5249dfae2d9d69a21bb6f',
    messagingSenderId: '404183473726',
    projectId: 'cw8-v2',
    authDomain: 'cw8-v2.firebaseapp.com',
    storageBucket: 'cw8-v2.firebasestorage.app',
  );
}
